export {
  createNextClawAppClient,
  type NextClawAppClient,
  type NextClawPanelAppNamespace,
} from "./nextclaw-app-client.utils.js";
export { NextClawClient } from "./nextclaw-client.manager.js";
export { NextClawClientError } from "./services/request.service.js";
export { McpService } from "./services/mcp.service.js";
export {
  FeatureControlsService,
  type ProductFeatureControlsView,
} from "./services/feature-controls.service.js";
export {
  CapabilityAccessService,
  type CapabilityGrantRequestView,
  type CapabilityGrantView,
  type DesktopHostStatusView,
} from "./services/capability-access.service.js";
export { AppPackagesClientService } from "./services/app-packages.service.js";
export { AppDataClientService } from "./services/app-data.service.js";
export { InboxDeliveriesService } from "./services/inbox-deliveries.service.js";
export { SystemObjectReferencesService } from "./services/system-object-references.service.js";
export { eventKeys } from "@nextclaw/shared";
export type {
  AgentRunSendIngressPayload,
  AppEvent,
  AppEventEnvelope,
  AppEventKey,
} from "@nextclaw/shared";
export type {
  NextClawAgentRunStreamHandler,
  NextClawAgentRunStreamOptions,
  NextClawAgentRunStreamSubscription,
} from "./services/agent-runs.service.js";
export type { ListSessionMessagesParams } from "./services/sessions.service.js";
export type {
  NextClawClientOptions,
  NextClawRealtimeHandler,
  NextClawRealtimeSubscribeOptions,
  NextClawRequestOptions,
  NextClawUploadOptions,
} from "./types/nextclaw-request.types.js";
export type {
  NextClawRealtimeEvent,
  NextClawRealtimeSubscription,
  NextClawWebSocketLike,
} from "./types/nextclaw-realtime.types.js";
export type {
  NextClawQueryParams,
  NextClawQueryValue,
  NextClawRequestMethod,
  NextClawTransport,
  NextClawTransportRequestInput,
  NextClawTransportUploadInput,
} from "./types/nextclaw-transport.types.js";
export type {
  AppPackageHostTarget,
  AppPackageList,
  AppDataDeleteResult,
  AppDataEntry,
  AppDataList,
  AppPackageOperationInput,
  AppPackageOperationList,
  AppPackageOperationStatus,
  AppPackageOperationView,
  AppPackageView,
  AgentBindingView,
  AgentCreateRequest,
  AgentDeleteResult,
  AgentProfileView,
  AgentUpdateRequest,
  ApiError,
  ApiResponse,
  AppMetaView,
  AuthEnabledUpdateRequest,
  AuthLoginRequest,
  AuthPasswordUpdateRequest,
  AuthSetupRequest,
  AuthStatusView,
  BootstrapStatusView,
  ChannelAuthConnectRequest,
  ChannelAuthConnectResult,
  ChannelAuthPollRequest,
  ChannelAuthPollResult,
  ChannelAuthStartRequest,
  ChannelAuthStartResult,
  ChatSessionTypesView,
  ConfigActionExecuteRequest,
  ConfigActionExecuteResult,
  ConfigMetaView,
  ConfigSchemaResponse,
  ConfigUiHints,
  ConfigView,
  CronActionResult,
  CronEnableRequest,
  CronJobView,
  CronListQuery,
  CronListStatus,
  CronListSummaryView,
  CronListView,
  CronRunRequest,
  MarketplaceInstalledView,
  McpConnectionCreateResult,
  McpConnectionRequest,
  McpConnectionTestResult,
  MarketplaceInstallRequest,
  MarketplaceInstallResult,
  MarketplaceItemType,
  MarketplaceItemView,
  MarketplaceListView,
  MarketplaceMcpContentView,
  MarketplaceMcpDoctorResult,
  MarketplaceMcpInstallRequest,
  MarketplaceMcpInstallResult,
  MarketplaceMcpManageRequest,
  MarketplaceMcpManageResult,
  MarketplaceRecommendationView,
  MarketplaceSceneView,
  MarketplaceScenesView,
  MarketplaceSkillContentView,
  MarketplaceSort,
  NcpSessionSkillsView,
  PanelAppAgentCapabilityView,
  PanelAppAgentGenerateObjectRequestView,
  PanelAppAgentGenerateObjectResultView,
  PanelAppAgentSendRequestView,
  PanelAppAgentSendResultView,
  PanelAppEntryView,
  PanelAppBridgeSessionCreateRequest,
  PanelAppBridgeSessionView,
  PanelAppCapabilityGrantView,
  PanelAppClientGrantView,
  PanelAppListView,
  ProviderAuthImportResult,
  ProviderAuthPollRequest,
  ProviderAuthPollResult,
  ProviderAuthStartRequest,
  ProviderAuthStartResult,
  ProviderConfigUpdate,
  ProviderConfigView,
  ProviderConnectionTestRequest,
  ProviderConnectionTestResult,
  ProviderCreateRequest,
  ProviderCreateResult,
  ProviderDeleteResult,
  ProviderInstanceView,
  ProviderTemplateView,
  ProviderTemplatesView,
  ProvidersView,
  ProjectAddExistingRequest,
  ProjectAgreementMaterial,
  ProjectCreateRequest,
  ProjectListView,
  ProjectTemplateView,
  ProjectView,
  CreateProjectWorkItemInput,
  CreateProjectWorkStateInput,
  ProjectWorkActivity,
  ProjectWorkActivityPage,
  ProjectWorkArtifactLink,
  ProjectWorkAttention,
  ProjectWorkItemDetail,
  ProjectWorkItemListEntry,
  ProjectWorkItemPage,
  ProjectWorkListInput,
  ProjectRecentArtifact,
  ProjectRecentArtifactPage,
  ProjectSkillMaterial,
  ProjectWorkState,
  ProjectWorkStateCategory,
  ProjectWorkSummary,
  UpdateProjectWorkItemInput,
  UpdateProjectWorkStateInput,
  RemoteAccessView,
  RemoteAccountProfileUpdateRequest,
  RemoteBrowserAuthPollRequest,
  RemoteBrowserAuthPollResult,
  RemoteBrowserAuthStartRequest,
  RemoteBrowserAuthStartResult,
  RemoteDoctorView,
  RemoteLoginRequest,
  RemoteServiceAction,
  RemoteServiceActionResult,
  RemoteSettingsUpdateRequest,
  RuntimeConfigUpdate,
  RuntimeControlActionResult,
  RuntimeControlView,
  RuntimeVerificationRecordListView,
  SearchConfigUpdate,
  SearchConfigView,
  ServiceActionGrantBatchRequestView,
  ServiceActionGrantView,
  ServiceActionGrantListView,
  ServiceActionInvokeResultView,
  ServiceActionListView,
  ServiceAppListView,
  ServiceAppRecordView,
  PortableRuntimeAcceptanceContractApiView,
  PortableRuntimeAcceptanceExportApiView,
  PortableRuntimeAcceptanceStatusApiView,
  SecretsConfigUpdate,
  SecretsView,
  ServerPathBrowseView,
  ServerPathDirectoryCreateRequest,
  ServerPathDirectoryCreateView,
  ServerPathEntryDeleteView,
  ServerPathEntryRenameRequest,
  ServerPathEntryRenameView,
  ServerPathFileCreateRequest,
  ServerPathFileCreateView,
  ServerPathFilesUploadView,
  ServerPathReadView,
  ServerPathSearchEntryView,
  ServerPathSearchView,
  ServerPathWatchRequest,
  ServerPathWatchView,
  SessionPatchUpdate,
  UiNcpAssetPutView as NcpAssetPutView,
  UiNcpSessionListView,
  UiNcpSessionMessagesView,
  UiNcpSessionQueuedInputView,
  UiNcpSessionQueuedInputsView,
  UiNcpSessionPendingInputView,
  UiNcpSessionPendingInputsView,
  UiNcpSessionTokenUsageView,
  UiServerEvent,
} from "@nextclaw/server";
export type {
  NcpEndpointEvent,
  NcpMessageAbortPayload,
  NcpRunHandle,
  NcpSessionSummary,
  NcpStreamRequestPayload,
} from "@nextclaw/ncp";
export type { UpdateSnapshot } from "@nextclaw/shared";
export type {
  SystemObjectReferenceDisplayText,
  SystemObjectReferenceGroupDescriptor,
  SystemObjectReferenceGroupIcon,
  SystemObjectReferenceGroupView,
  InboxDelivery,
  InboxDeliveryListView,
  InboxDeliveryStateAction,
  SystemObjectReferenceItem,
  SystemObjectReferenceListView,
  SystemObjectResolvedReference,
} from "@nextclaw/shared";
export type ChannelConfigUpdate = Record<string, unknown>;
export type PanelAppPreferencesUpdateView = {
  favorite?: boolean;
  mainSidebar?: boolean;
};
